dConnectJavascriptApp/dconnect.manifest, dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/canvas.js, dConnectJavascriptApp/js/profile/mediastreamrecording.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.0.0.js, dConnectSDKForJavascript/dconnectsdk-2.0.0.js
Add a constant for Availability API.
=> Feature availability api

dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/battery.js, dConnectJavascriptApp/js/profile/camera.js, dConnectJavascriptApp/js/profile/canvas.js, dConnectJavascriptApp/js/profile/connect.js, dConnectJavascriptApp/js/profile/deviceorientation.js, dConnectJavascriptApp/js/profile/dice.js, dConnectJavascriptApp/js/profile/drivecontroller.js, dConnectJavascriptApp/js/profile/file.js, dConnectJavascriptApp/js/profile/filedescriptor.js, dConnectJavascriptApp/js/profile/light.js, dConnectJavascriptApp/js/profile/mediaplayer.js, dConnectJavascriptApp/js/profile/mediastreamrecording.js, dConnectJavascriptApp/js/profile/mhealth.js, dConnectJavascriptApp/js/profile/notification.js, dConnectJavascriptApp/js/profile/phone.js, dConnectJavascriptApp/js/profile/proximity.js, dConnectJavascriptApp/js/profile/remotecontroller.js, dConnectJavascriptApp/js/profile/servicediscovery.js, dConnectJavascriptApp/js/profile/settings.js, dConnectJavascriptApp/js/profile/sphero.js, dConnectJavascriptApp/js/profile/system.js, dConnectJavascriptApp/js/profile/temperature.js, dConnectJavascriptApp/js/profile/vibration.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.0.0.js, dConnectJavascriptApp/js/sdk/util.js, dConnectSDKForJavascript/dconnectsdk-2.0.0.js
=> Modify service discovery

dConnectJavascriptApp/js/profile/mediaplayer.js
=> Bugfix mediaplayer profile

dConnectJavascriptApp/js/profile/filedescriptor.js, dConnectJavascriptApp/js/profile/keyevent.js, dConnectJavascriptApp/js/profile/mediastreamrecording.js, dConnectJavascriptApp/js/profile/notification.js, dConnectJavascriptApp/js/profile/touch.js
name modification, such as "Device Top" button of demoWebSite.
=> Modify profile page state

dConnectJavascriptApp/js/profile/light.js, dConnectSDKForJavascriptTest/tests/profiles/media_player_normal.js
Additional UI to adjust the brightness to lightProfile of UI.
=> Modify light profile

README.md
=> 英語版の README に日本語の文章が混じっていた

dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.0.0.js, dConnectSDKForJavascript/dconnectsdk-2.0.0.js
=> Modify sdk

dConnectSDKForJavascriptTest/tests/profiles/canvas_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/canvas_normal.js, dConnectSDKForJavascriptTest/tests/profiles/media_player_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/media_player_normal.js, dConnectSDKForJavascriptTest/tests/profiles/notification_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/notification_normal.js, dConnectSDKForJavascriptTest/tests/profiles/proximity_normal.js
Modify qunit by chromecast and host
=> Modify qunit by chromecast and host

dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.0.0.js, dConnectSDKForJavascript/dconnectsdk-2.0.0.js, dConnectSDKForJavascriptTest/dconnectsdk-2.0.0.js
- Monitor whether a websocket connection is open every one second.
- Open a websocket when DeviceConnectManager is launched.
=> Modify websocket connection

dConnectJavascriptApp/js/profile/notification.js
Behavior modification of the Notification when EnterKey
=> Behavior modification of the Notification when EnterKey

dConnectJavascriptApp/js/profile/file.js, dConnectJavascriptApp/js/profile/mediastreamrecording.js, dConnectSDKForJavascriptTest/dconnect-test-config.js, dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/index.html, dConnectSDKForJavascriptTest/tests/profiles/file_normal.js, dConnectSDKForJavascriptTest/tests/profiles/mediastream_recording_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/mediastream_recording_normal.js, dConnectSDKForJavascriptTest/tests/theta_record_test.html, dConnectSDKForJavascriptTest/tests/theta_takepicture_test.html
=> Feature add theta test

dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/filedescriptor.js, dConnectJavascriptApp/js/profile/mediastreamrecording.js, dConnectJavascriptApp/js/profile/servicediscovery.js, dConnectJavascriptApp/js/profile/system.js, dConnectJavascriptApp/js/sdk/util.js
=> Modify demo website

dConnectSDKForJavascript/dconnectsdk-2.0.0.js
Added a dConnect.getHost method
=> Added a dConnect.getHost method

dConnectJavascriptApp/js/profile/light.js
=> Bugfix light profile ui

dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/humidity.js, dConnectJavascriptApp/js/profile/illuminance.js, dConnectJavascriptApp/js/profile/powermeter.js
=> Feature add profile for fplug

dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/omnidirectionalimage.js, dConnectSDKForJavascriptTest/dconnect-test-config.js, dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/index.html, dConnectSDKForJavascriptTest/tests/extra_profiles/omnidirectional_image_abnormal.js, dConnectSDKForJavascriptTest/tests/theta_omnidirectional_image_test.html
=> Feature add theta test extended

dConnectJavascriptApp/js/demo.js
=> Modify merge miss

dConnectJavascriptApp/js/profile/canvas.js, dConnectSDKForJavascriptTest/dconnect-test-util.js
=> Modify foreground canvas

dConnectSDKForJavascript/dconnectsdk-2.0.0.js
=> Bugfix event callback

dConnectJavascriptApp/js/profile/tv.js
=> Modify change channel action

dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/index.html, dConnectSDKForJavascriptTest/tests/extra_profiles/tv_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/tv_normal.js, dConnectSDKForJavascriptTest/tests/irkit_virtual_light_test.html, dConnectSDKForJavascriptTest/tests/irkit_virtual_tv_test.html
Feature irkit virtual devices qunit
=> Feature irkit virtual devices qunit

README.md, readme.ja.md
=> Modify readme files

dConnectJavascriptApp/js/profile/file.js
=> Modify remove directory

dConnectSDKForJavascriptTest/dconnect-test-config.js, dConnectSDKForJavascriptTest/tests/theta_omnidirectional_image_test.html
=> Modify omni settings

dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/file.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.0.0.js, dConnectSDKForJavascript/dconnectsdk-2.0.0.js, dConnectSDKForJavascriptTest/dconnect-test-config.js, dConnectSDKForJavascriptTest/dconnectsdk-2.0.0.js, dConnectSDKForJavascriptTest/tests/theta_omnidirectional_image_test.html
=> Modify ios9 contents blocker

dConnectJavascriptApp/js/profile/canvas.js
=> Modify canvas profile interface

dConnectJavascriptApp/js/profile/proximity.js
=> Modify proximity profile

dConnectJavascriptApp/js/profile/omnidirectionalimage.js
=> Modify ui for theta s

dConnectSDKForJavascriptTest/index.html
Add HVC-C2W and HVC-P device plug-in.
=> Add HVC-C2W and HVC-P device plug-in

dConnectJavascriptApp/js/profile/mediastreamrecording.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.0.0.js, dConnectSDKForJavascript/dconnectsdk-2.0.0.js, dConnectSDKForJavascriptTest/dconnectsdk-2.0.0.js, dConnectSDKForJavascriptTest/tests/profiles/mediastream_recording_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/mediastream_recording_normal.js
Modify mediastream recording profile
=> Modify mediastream recording profile

dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/servicediscovery.js, dConnectJavascriptApp/js/profile/system.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.0.0.js, dConnectJavascriptApp/js/sdk/util.js, dConnectSDKForJavascript/dconnectsdk-2.0.0.js, dConnectSDKForJavascriptTest/dconnectsdk-2.0.0.js, dConnectSDKForJavascriptTest/tests/profiles/system_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/system_normal.js
Modify system profile protection
=> Modify system profile protection

dConnectJavascriptApp/js/profile/file.js
=> File Send画面にURIを指定するUIを追加

dConnectJavascriptApp/js/profile/omnidirectionalimage.js
* iOSで、demoWebSiteにて、ROI Image ServiceのomnidirectionalImageでX-coodinateのStart Incrementが最後まで成功すること。
* アンダーフローが発生しないようにした。
=> パラメータの小数点を第3位で四捨五入

dConnectJavascriptApp/js/profile/omnidirectionalimage.js, dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/tests/profiles/media_player_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/media_player_normal.js
* Host,ChromeCast(iOS,Android)でMediaPlayer周りのQUnitを実行
=> MediaPlayer周りのQUnit調整

dConnectJavascriptApp/js/profile/health.js, dConnectJavascriptApp/js/profile/messagehook.js, dConnectJavascriptApp/js/profile/videochat.js, dConnectSDKForJavascriptTest/tests/extra_profiles/health_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/health_normal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/messagehook_normal.js, dConnectSDKForJavascriptTest/tests/profiles/videochat_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/videochat_normal.js
* attributeの頭にonが付いていないものにonをつけるようにした。
* GotAPIで定義されているものに関しては、定義されているものと「on」を付加したものの二つをサポートするようにした。
* /health/heartと/health/onHeartで動作するようにした。
* Health
* MessageHook
* VideoChat
=> イベントURLのattributeの修正

dConnectJavascriptApp/js/profile/airconditioner.js, dConnectJavascriptApp/js/profile/powermeter.js, dConnectSDKForJavascriptTest/tests/extra_profiles/airconditioner_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/airconditioner_normal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/powermeter_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/powermeter_normal.js
* AirConditionerおよびPowerMeterの冗長な単語を修正
* "operation"、"value"の削除
=> 冗長なattribute名とパラメータ名の修正

dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/humandetection.js, dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/tests/extra_profiles/human_detection_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/human_detection_normal.js, dConnectSDKForJavascriptTest/tests/hvcc_test.html
- HumanDetect→HumanDetectionへプロファイル名を変更。
- 人感検出用のAPIをHumanDetectionプロファイルへ追加。
=> HumanDetectionプロファイルの修正

dConnectJavascriptApp/js/profile/touch.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.2.0.js, dConnectSDKForJavascript/dconnectsdk-2.2.0.js, dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/dconnectsdk-2.2.0.js, dConnectSDKForJavascriptTest/tests/profiles/touch_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/touch_normal.js, dConnectSDKForJavascriptTest/tests/sony_sw_test.html, dConnectSDKForJavascriptTest/tests/wear_test.html
* タッチの状態を全て取得するAPIの追加
* Host,AndroidWear,SonySWで対応
=> TouchProfileの改修

dConnectJavascriptApp/js/profile/keyevent.js, dConnectJavascriptApp/js/profile/touch.js, dConnectJavascriptApp/js/sdk/dconnectsdk-2.2.0.js, dConnectSDKForJavascript/dconnectsdk-2.2.0.js, dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/dconnectsdk-2.2.0.js, dConnectSDKForJavascriptTest/tests/profiles/key_event_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/key_event_normal.js, dConnectSDKForJavascriptTest/tests/profiles/touch_abnormal.js, dConnectSDKForJavascriptTest/tests/profiles/touch_normal.js, dConnectSDKForJavascriptTest/tests/sony_sw_test.html, dConnectSDKForJavascriptTest/tests/wear_test.html
* KeyEventの状態を同時に取得できるonKeyChangeAPI用のUIとQUnitを追加。
=> KeyEventプロファイルの更新

dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/drivecontroller.js, dConnectJavascriptApp/js/profile/gpio.js
=> GPIO動作確認用UIの修正

dConnectJavascriptApp/js/profile/drivecontroller.js
* FaBoデバイスプラグインで作られたロボットカーを操作できるようにした。
=> DriveControllerプロファイルの操作画面を修正

dConnectJavascriptApp/js/profile/fabo.js
* dConnectJavascriptAppでI2Cを操作できるようにした。
=> I2Cのデバイスを追加

dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/servicediscovery.js, dConnectJavascriptApp/js/sdk/util.js
* dConnectJavascriptApp初回起動時に、ConsoleにてjQueryのエラーが出ていたため修正。
=> jQueryのListViewのrefresh時のエラー修正

dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/index.html, dConnectSDKForJavascriptTest/tests/extra_profiles/fabo_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/fabo_normal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/gpio_abnormal.js, dConnectSDKForJavascriptTest/tests/fabo_test.html
=> FaBoProfileの自動テストを追加

dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/fabo.js, dConnectJavascriptApp/js/profile/gpio.js, dConnectJavascriptApp/js/profile/keyboard.js, dConnectJavascriptApp/js/profile/mouse.js, dConnectSDKForJavascriptTest/dconnect-test-util.js, dConnectSDKForJavascriptTest/index.html, dConnectSDKForJavascriptTest/tests/extra_profiles/fabo_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/fabo_normal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/gpio_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/keyboard_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/keyboard_normal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/mouse_abnormal.js, dConnectSDKForJavascriptTest/tests/extra_profiles/mouse_normal.js, dConnectSDKForJavascriptTest/tests/fabo_test.html, dConnectSDKForJavascriptTest/tests/hogp_test.html
* Mouseプロファイルの操作画面とKeyboardプロファイルの操作画面を追加
=> HOGPプロファイル操作確認UIの追加

dConnectSDKForJavascriptTest/tests/profiles/mediastream_recording_normal.js
=> onRecordingChangeのQUnitを追加

dConnectJavascriptApp/js/profile/connection.js, dConnectJavascriptApp/js/profile/setting.js, dConnectJavascriptApp/js/profile/sphero.js
* RFC3339形式で日付を設定するように修正
* SettingのUI画面遷移する時に、必要のないイベントを解除していた処理の修正。
=> RFC3339形式で日付を設定するように修正

dConnectJavascriptApp/js/profile/camera.js
* Max/Minの時は「Max」パラメータをmovementに指定するようにする。
=> CameraProfileの仕様変更対応

dConnectSDKForJavascriptTest/tests/extra_profiles/camera_normal.js
start -> in-start
stop -> in-stop
=> Camera Zoom APIのリクエストパラメータ値の変更対応

dConnectJavascriptApp/index.html, dConnectJavascriptApp/js/profile/phone.js, dConnectSDKForJavascriptTest/tests/profiles/phone_abnormal.js
* Phoneプロファイルの更新に伴い動作確認できるUIを追加。
=> Phoneプロファイルのテスト追加

dConnectSDKForJavascriptTest/dconnect-test-util.js
=> 未定義メソッドエラーが返された場合はテストOKとする

dConnectJavascriptApp/js/profile/canvas.js
* CanvasプロファイルでMIME-Typeを設定できるようにした。
=> demoWebSiteでmimeTypeを設定できるようにした

dConnectJavascriptApp/js/profile/canvas.js, dConnectJavascriptApp/js/profile/file.js, dConnectJavascriptApp/js/profile/notification.js, dConnectJavascriptApp/js/sdk/util.js
Javascript の構文エラーのために、Canvas, Notification プロファイルでの POST 用の UI が表示されなかった問題を修正。
=> 不具合修正: POST用のUIが表示されない

dConnectJavascriptApp/js/profile/setting.js
「Set volume of 〜」のボタン押下時にエラーが返される問題を修正。
=> 不具合修正: PUT /setting/sound/volume のパス指定

dConnectJavascriptApp/js/demo.js, dConnectJavascriptApp/js/profile/mediastreamrecording.js, dConnectJavascriptApp/js/profile/omnidirectionalimage.js
* 以下のプロファイルのUIをhttps対応した。
* MediaStreamRecording
* OmnidirectionalImage
=> Preview用UIのhttps対応
